name: CI / CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s ./tests -p "test.py"

  verify_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify test job success
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Tests passed. Proceeding with deployment."
          else
            echo "Tests failed. Aborting deployment."
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hyperionduck/mariadbflask:latest

  notify:
    needs: [test, verify_and_deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify success
        if: success()
        run: |
          echo "Pipeline completed successfully!"
          echo "Code has been tested and pushed to the main branch."

      - name: Notify failure
        if: failure()
        run: |
          echo "Pipeline failed. The push to the main branch was unsuccessful."
          echo "Please check the test results and fix any issues before pushing again."